name = "Descent: Badlands"
author = "Avalon Servers"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "302e48bd93c203e8610a2269c8246a40495945557e856cb7ac5382dcb06eed22"

[versions]
forge = "47.4.0"
minecraft = "1.20.1"
