name = "Descent: Badlands"
author = "Avalon Servers"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "aeaefa4d49720feefa2d67be5f89b3671d9240fd1ae0c34dc40f2cfc6d2342a9"

[versions]
forge = "47.4.0"
minecraft = "1.20.1"
