name = "Descent: Frozen Hell"
author = "Avalon Servers"
version = "1.31.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6b79980aec4bcc35bb09b82d3ee86c3ffe5ae25a765eb81bc327dc3111ea4b7c"

[versions]
forge = "14.23.5.2860"
minecraft = "1.12.2"
