name = "Descent: Industry"
author = "Avalon Servers"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "bfca979a6f4ca7ed0cac5d4ff0078ebe5012081fcece034e22f0d1d9fe70f5f1"

[versions]
forge = "10.13.4.1614"
minecraft = "1.7.10"
